server:
  port: 8030
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql:///0611-springboot?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=UTF-8
  application:
    name: matadata
logging:
  level:
    com:
      zr: debug
mybatis:
  mapper-locations: classpath:mybatis-mapper/*Mapper.xml