server:
  port: 8010
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://39.97.182.213:3306/operate_platform2?serverTimezone=GMT%2B8&allowMultiQueries=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
  application:
    name: matadata
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    com:
      zr: debug
mybatis:
  mapper-locations: classpath:mybatis-mapper/*Mapper.xml